// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: square.proto

package squareTest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type SquareNumber struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// reserved 3, 4 , 5 to 9; 保留或廢棄欄位
	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *SquareNumber) Reset() {
	*x = SquareNumber{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareNumber) ProtoMessage() {}

func (x *SquareNumber) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareNumber.ProtoReflect.Descriptor instead.
func (*SquareNumber) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{0}
}

func (x *SquareNumber) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

// The response message containing the greetings
type SquareReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
}

func (x *SquareReply) Reset() {
	*x = SquareReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareReply) ProtoMessage() {}

func (x *SquareReply) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareReply.ProtoReflect.Descriptor instead.
func (*SquareReply) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{1}
}

func (x *SquareReply) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

// Chat
type CheetMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	SendTime int64  `protobuf:"varint,2,opt,name=sendTime,proto3" json:"sendTime,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CheetMsg) Reset() {
	*x = CheetMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheetMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheetMsg) ProtoMessage() {}

func (x *CheetMsg) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheetMsg.ProtoReflect.Descriptor instead.
func (*CheetMsg) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{2}
}

func (x *CheetMsg) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CheetMsg) GetSendTime() int64 {
	if x != nil {
		return x.SendTime
	}
	return 0
}

func (x *CheetMsg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CheetRespond struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Respond bool `protobuf:"varint,1,opt,name=respond,proto3" json:"respond,omitempty"`
}

func (x *CheetRespond) Reset() {
	*x = CheetRespond{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheetRespond) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheetRespond) ProtoMessage() {}

func (x *CheetRespond) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheetRespond.ProtoReflect.Descriptor instead.
func (*CheetRespond) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{3}
}

func (x *CheetRespond) GetRespond() bool {
	if x != nil {
		return x.Respond
	}
	return false
}

// MapLog
type MapLogDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  int32 `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude int32 `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *MapLogDate) Reset() {
	*x = MapLogDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_square_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MapLogDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapLogDate) ProtoMessage() {}

func (x *MapLogDate) ProtoReflect() protoreflect.Message {
	mi := &file_square_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapLogDate.ProtoReflect.Descriptor instead.
func (*MapLogDate) Descriptor() ([]byte, []int) {
	return file_square_proto_rawDescGZIP(), []int{4}
}

func (x *MapLogDate) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *MapLogDate) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_square_proto protoreflect.FileDescriptor

var file_square_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x08, 0x43, 0x68, 0x65,
	0x65, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x28, 0x0a, 0x0c, 0x43,
	0x68, 0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x46, 0x0a, 0x0a, 0x4d, 0x61, 0x70, 0x4c, 0x6f, 0x67, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x32, 0x8e, 0x02,
	0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x3d, 0x0a, 0x06,
	0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x12, 0x18, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x1a, 0x17, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x4c,
	0x69, 0x73, 0x74, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x18, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x1a, 0x17, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x30, 0x01, 0x12, 0x3a, 0x0a, 0x04, 0x43, 0x68, 0x61, 0x74, 0x12, 0x14, 0x2e, 0x43, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x68, 0x65, 0x65, 0x74, 0x4d, 0x73, 0x67,
	0x1a, 0x18, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x68,
	0x65, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x64, 0x22, 0x00, 0x28, 0x01, 0x12, 0x3e,
	0x0a, 0x06, 0x4d, 0x61, 0x70, 0x4c, 0x6f, 0x67, 0x12, 0x16, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75,
	0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x61, 0x70, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x65,
	0x1a, 0x16, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4d, 0x61,
	0x70, 0x4c, 0x6f, 0x67, 0x44, 0x61, 0x74, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0f,
	0x5a, 0x0d, 0x2e, 0x2f, 0x3b, 0x73, 0x71, 0x75, 0x61, 0x72, 0x65, 0x54, 0x65, 0x73, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_square_proto_rawDescOnce sync.Once
	file_square_proto_rawDescData = file_square_proto_rawDesc
)

func file_square_proto_rawDescGZIP() []byte {
	file_square_proto_rawDescOnce.Do(func() {
		file_square_proto_rawDescData = protoimpl.X.CompressGZIP(file_square_proto_rawDescData)
	})
	return file_square_proto_rawDescData
}

var file_square_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_square_proto_goTypes = []interface{}{
	(*SquareNumber)(nil), // 0: Calculator.SquareNumber
	(*SquareReply)(nil),  // 1: Calculator.SquareReply
	(*CheetMsg)(nil),     // 2: Calculator.CheetMsg
	(*CheetRespond)(nil), // 3: Calculator.CheetRespond
	(*MapLogDate)(nil),   // 4: Calculator.MapLogDate
}
var file_square_proto_depIdxs = []int32{
	0, // 0: Calculator.Calculator.Square:input_type -> Calculator.SquareNumber
	0, // 1: Calculator.Calculator.ListFeatures:input_type -> Calculator.SquareNumber
	2, // 2: Calculator.Calculator.Chat:input_type -> Calculator.CheetMsg
	4, // 3: Calculator.Calculator.MapLog:input_type -> Calculator.MapLogDate
	1, // 4: Calculator.Calculator.Square:output_type -> Calculator.SquareReply
	1, // 5: Calculator.Calculator.ListFeatures:output_type -> Calculator.SquareReply
	3, // 6: Calculator.Calculator.Chat:output_type -> Calculator.CheetRespond
	4, // 7: Calculator.Calculator.MapLog:output_type -> Calculator.MapLogDate
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_square_proto_init() }
func file_square_proto_init() {
	if File_square_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_square_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareNumber); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_square_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_square_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheetMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_square_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheetRespond); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_square_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MapLogDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_square_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_square_proto_goTypes,
		DependencyIndexes: file_square_proto_depIdxs,
		MessageInfos:      file_square_proto_msgTypes,
	}.Build()
	File_square_proto = out.File
	file_square_proto_rawDesc = nil
	file_square_proto_goTypes = nil
	file_square_proto_depIdxs = nil
}
